tags:
  - user-settings-controller
summary: Retrieve user settings
description: Retrieve user settings
externalDocs:
  description: ''
  url: https://
operationId: getUserSettings
responses:
  '200':
    $ref: ../../components/responses/ok/userSettings/userSettings.yaml
  '401':
    $ref: ../../components/responses/unauthorized/common/empty.yaml
  '403':
    $ref: ../../components/responses/forbidden/common/empty.yaml
  '404':
    $ref: ../../components/responses/notFound/common/empty.yaml