tags:
  - role-controller
summary: Update a role
description: Update the role specified in the path as described in the request body
externalDocs:
  description: ''
  url: https://
operationId: updateRole
requestBody:
  $ref: ../../../components/requestBodies/roles/role.yaml
responses:
  '200':
    $ref: ../../../components/responses/ok/roles/role.yaml
  '201':
    $ref: ../../../components/responses/created/common/empty.yaml
  '401':
    $ref: ../../../components/responses/unauthorized/common/empty.yaml
  '403':
    $ref: ../../../components/responses/forbidden/common/empty.yaml
  '404':
    $ref: ../../../components/responses/notFound/common/empty.yaml