openapi: 3.0.0
info:
  title: Entando Core APIs
  description: Entando Core APIs
  termsOfService: 'https://'
  contact:
    name: Walter Caffiero
    url: 'https://'
    email: w.caffiero@entando.com
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
  version: 7.0.0
servers:
  - url: /entando-de-app/api
    description: Entando 7.0 API base path
paths:
  /activityStream:
    summary: Activity stream operations
    description: End-point to access and manipulate the activity stream
    get:
      tags:
        - activity-stream-controller
      summary: Retrieve the activity stream
      description: Retrieve the activity stream's records filtered by query parameters
      externalDocs:
        description: ''
        url: 'https://'
      operationId: getActivityStream
      parameters:
        - $ref: '#/components/parameters/allowedValues'
        - $ref: '#/components/parameters/attribute'
        - $ref: '#/components/parameters/entityAttr'
        - $ref: '#/components/parameters/operator'
        - $ref: '#/components/parameters/order'
        - $ref: '#/components/parameters/type'
        - $ref: '#/components/parameters/value'
        - $ref: '#/components/parameters/direction'
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
        - $ref: '#/components/parameters/sort'
      responses:
        '200':
          $ref: '#/components/responses/activityStream'
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '404':
          $ref: '#/components/responses/notFound'
  '/activityStream/{recordId}/comments':
    summary: Activity stream record's comments collection operations
    description: End-point to access and manipulate the activity stream record's comments collection
    parameters:
      - $ref: '#/components/parameters/activityStreamRecordId'
    post:
      tags:
        - activity-stream-controller
      summary: Add a comment to an activity stream record
      description: Add the comment to the activity stream record specified in the path as described in the request body
      externalDocs:
        description: ''
        url: 'https://'
      operationId: addComment
      requestBody:
        $ref: '#/components/requestBodies/activityStreamRecordComment'
      responses:
        '200':
          $ref: '#/components/responses/activityStreamRecord'
        '201':
          $ref: '#/components/responses/created'
        '401':
          $ref: '#/components/responses/unauthorized'
        '403':
          $ref: '#/components/responses/forbidden'
        '404':
          $ref: '#/components/responses/notFound'
components:
  schemas:
    activityStreamRecord:
      title: Activity stream record
      type: object
      properties:
        actionName:
          type: string
        comments:
          type: array
          items:
            $ref: '#/components/schemas/activityStreamCommentInfo'
        createdAt:
          type: string
          format: date-time
        id:
          type: integer
          format: int32
        likes:
          type: array
          items:
            $ref: '#/components/schemas/activityStreamLikeInfo'
        namespace:
          type: string
        parameters:
          type: object
          additionalProperties:
            type: string
        updatedAt:
          type: string
          format: date-time
        username:
          type: string
    activityStreamCommentInfo:
      title: Activity stream record comment info
      type: object
      properties:
        commentDate:
          type: string
          format: date-time
        commentText:
          type: string
        displayName:
          type: string
        id:
          type: integer
          format: int32
        username:
          type: string
    activityStreamLikeInfo:
      title: Activity stream record like info
      type: object
      properties:
        displayName:
          type: string
        username:
          type: string
    filter:
      title: Filter
      type: object
      properties:
        attribute:
          type: string
        entityAttr:
          type: string
        operator:
          type: string
        order:
          type: string
        type:
          type: string
        value:
          type: string
        allowedValues:
          type: array
          items:
            type: string
    pagedRestResponse:
      title: Paged REST response
      type: object
      allOf:
        - $ref: '#/components/schemas/restResponseListPayload'
        - properties:
            metadata:
              $ref: '#/components/schemas/paginationMetadata'
    paginationMetadata:
      title: Pagination metadata
      type: object
      properties:
        page:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
        lastPage:
          type: integer
          format: int32
        totalItems:
          type: integer
          format: int32
        sort:
          type: string
        direction:
          type: string
        filters:
          type: array
          items:
            $ref: '#/components/schemas/filter'
        additionalParams:
          type: object
          additionalProperties:
            type: string
    restError:
      title: REST error
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    restResponse:
      title: REST response
      type: object
      properties:
        payload:
          type: object
        metadata:
          type: object
        errors:
          type: array
          items:
            $ref: '#/components/schemas/restError'
    restResponseListPayload:
      title: REST response list payload
      type: object
      allOf:
        - $ref: '#/components/schemas/restResponse'
        - properties:
            payload:
              type: array
              items:
                type: object
    restResponseListPayloadMapMetadata:
      title: REST response list payload map metadata
      type: object
      allOf:
        - $ref: '#/components/schemas/restResponseMapMetadata'
        - $ref: '#/components/schemas/restResponseListPayload'
    restResponseMapMetadata:
      title: REST response map metadata
      type: object
      allOf:
        - $ref: '#/components/schemas/restResponse'
        - properties:
            metadata:
              type: object
              additionalProperties:
                type: string
    restResponseMapPayload:
      title: REST response map payload
      type: object
      allOf:
        - $ref: '#/components/schemas/restResponse'
        - properties:
            payload:
              type: object
              additionalProperties:
                type: string
  responses:
    activityStream:
      description: OK
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/pagedRestResponse'
              - properties:
                  payload:
                    type: array
                    items:
                      $ref: '#/components/schemas/activityStreamRecord'
    activityStreamRecord:
      description: OK
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/restResponse'
              - properties:
                  payload:
                    $ref: '#/components/schemas/activityStreamRecord'
    created:
      description: Created
    forbidden:
      description: Forbidden
    notFound:
      description: Not found
    unauthorized:
      description: Unauthorized
  parameters:
    activityStreamRecordId:
      name: recordId
      in: path
      description: ''
      required: true
      schema:
        type: integer
        format: int32
    allowedValues:
      name: 'filters[0].allowedValues'
      in: query
      description: ''
      style: form
      explode: true
      schema:
        type: array
        items:
          type: string
    attribute:
      name: 'filters[0].attribute'
      in: query
      description: ''
      schema:
        type: string
    direction:
      name: direction
      in: query
      description: ''
      schema:
        type: string
    entityAttr:
      name: 'filters[0].entityAttr'
      in: query
      description: ''
      schema:
        type: string
    operator:
      name: 'filters[0].operator'
      in: query
      description: ''
      schema:
        type: string
    order:
      name: 'filters[0].order'
      in: query
      description: ''
      schema:
        type: string
    page:
      name: page
      in: query
      description: ''
      schema:
        type: integer
        format: int32
    pageSize:
      name: pageSize
      in: query
      description: ''
      schema:
        type: integer
        format: int32
    sort:
      name: sort
      in: query
      description: ''
      schema:
        type: string
    type:
      name: 'filters[0].type'
      in: query
      description: ''
      schema:
        type: string
    value:
      name: 'filters[0].value'
      in: query
      description: ''
      schema:
        type: string
  examples: {}
  requestBodies:
    activityStreamRecordComment:
      description: Activity stream record comment
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              comment:
                type: string
              recordId:
                type: integer
                format: int32
  headers: {}
  securitySchemes:
    entando:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /auth/realms/entando/protocol/openid-connect/auth
          tokenUrl: /auth/realms/entando/protocol/openid-connect/token
          scopes: {}
  links: {}
  callbacks: {}
security:
  - entando: []
tags:
  - name: activity-stream-controller
    description: Activity stream operations
externalDocs:
  description: ''
  url: 'https://'