openapi: 3.0.0
info:
  title: Entando Core APIs
  description: Entando Core APIs
  termsOfService: 'https://'
  contact:
    name: Walter Caffiero
    url: 'https://'
    email: w.caffiero@entando.com
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
  version: 7.0.0
servers:
  - url: /entando-de-app/api
    description: Entando 7.0 API base path
paths: {}
components:
  schemas:
    restError:
      title: REST error
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    restResponse:
      title: REST response
      type: object
      properties:
        payload:
          type: object
        metadata:
          type: object
        errors:
          type: array
          items:
            $ref: '#/components/schemas/restError'
    restResponseListPayload:
      title: REST response list payload
      type: object
      allOf:
        - $ref: '#/components/schemas/restResponse'
        - properties:
            payload:
              type: array
              items:
                type: object
    restResponseListPayloadMapMetadata:
      title: REST response list payload map metadata
      type: object
      allOf:
        - $ref: '#/components/schemas/restResponseMapMetadata'
        - $ref: '#/components/schemas/restResponseListPayload'
    restResponseMapMetadata:
      title: REST response map metadata
      type: object
      allOf:
        - $ref: '#/components/schemas/restResponse'
        - properties:
            metadata:
              type: object
              additionalProperties:
                type: string
    restResponseMapPayload:
      title: REST response map payload
      type: object
      allOf:
        - $ref: '#/components/schemas/restResponse'
        - properties:
            payload:
              type: object
              additionalProperties:
                type: string
  responses: {}
  parameters: {}
  examples: {}
  requestBodies: {}
  headers: {}
  securitySchemes:
    entando:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /auth/realms/entando/protocol/openid-connect/auth
          tokenUrl: /auth/realms/entando/protocol/openid-connect/token
          scopes: {}
  links: {}
  callbacks: {}
security:
  - entando: []
tags:
  - name: ''
externalDocs:
  description: ''
  url: 'https://'