tags:
  - reload-configuration-controller
summary: Reload the configuration
description: Reload the configuration
externalDocs:
  description: ''
  url: https://
operationId: reloadConfiguration
responses:
  '200':
    $ref: ../../components/responses/ok/restResponse/restResponse.yaml
  '201':
    $ref: ../../components/responses/created/common/empty.yaml
  '401':
    $ref: ../../components/responses/unauthorized/common/empty.yaml
  '403':
    $ref: ../../components/responses/forbidden/common/empty.yaml
  '404':
    $ref: ../../components/responses/notFound/common/empty.yaml