tags:
  - user-settings-controller
summary: Update user settings
description: Update user settings
externalDocs:
  description: ''
  url: https://
operationId: updateUserSettings
requestBody:
  $ref: ../../components/requestBodies/userSettings/userSettings.yaml
responses:
  '200':
    $ref: ../../components/responses/ok/userSettings/userSettings.yaml
  '201':
    $ref: ../../components/responses/created/common/empty.yaml
  '401':
    $ref: ../../components/responses/unauthorized/common/empty.yaml
  '403':
    $ref: ../../components/responses/forbidden/common/empty.yaml
  '404':
    $ref: ../../components/responses/notFound/common/empty.yaml