tags:
  - page-configuration-controller
summary: Update a page configuration
description: Update the configuration of the page specified in the path
externalDocs:
  description: ''
  url: https://
operationId: updatePageConfiguration
responses:
  '200':
    $ref: ../../../../../components/responses/ok/pages/pageConfiguration.yaml
  '201':
    $ref: ../../../../../components/responses/created/common/empty.yaml
  '401':
    $ref: ../../../../../components/responses/unauthorized/common/empty.yaml
  '403':
    $ref: ../../../../../components/responses/forbidden/common/empty.yaml
  '404':
    $ref: ../../../../../components/responses/notFound/common/empty.yaml