tags:
  - gui-fragment-settings-controller
summary: Update the fragments settings
description: Update the fragments settings
externalDocs:
  description: ''
  url: https://
operationId: updateFragmentsSettings
responses:
  '200':
    $ref: ../../components/responses/ok/common/booleanMap.yaml
  '201':
    $ref: ../../components/responses/created/common/empty.yaml
  '401':
    $ref: ../../components/responses/unauthorized/common/empty.yaml
  '403':
    $ref: ../../components/responses/forbidden/common/empty.yaml
  '404':
    $ref: ../../components/responses/notFound/common/empty.yaml