tags:
  - page-settings-controller
summary: Retrieve the page settings
description: Retrieve the page settings
externalDocs:
  description: ''
  url: https://
operationId: getPageSettings
responses:
  '200':
    $ref: ../../components/responses/ok/restResponse/restResponseMapPayload.yaml
  '401':
    $ref: ../../components/responses/unauthorized/common/empty.yaml
  '403':
    $ref: ../../components/responses/forbidden/common/empty.yaml
  '404':
    $ref: ../../components/responses/notFound/common/empty.yaml