tags:
  - page-settings-controller
summary: Update the page settings
description: Update the page settings as described in the request body
externalDocs:
  description: ''
  url: https://
operationId: updatePageSettings
requestBody:
  $ref: ../../components/requestBodies/common/jsonMap.yaml
responses:
  '200':
    $ref: ../../components/responses/ok/restResponse/restResponseMapPayload.yaml
  '201':
    $ref: ../../components/responses/created/common/empty.yaml
  '401':
    $ref: ../../components/responses/unauthorized/common/empty.yaml
  '403':
    $ref: ../../components/responses/forbidden/common/empty.yaml
  '404':
    $ref: ../../components/responses/notFound/common/empty.yaml