description: OK
content:
  application/json:
    schema:
      allOf:
        - $ref: ../../../schemas/restResponse/restResponse.yaml
        - properties:
            payload:
              $ref: ../../../schemas/pages/pageConfiguration.yaml